# Generated by Django 3.2.20 on 2023-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ere', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
